services:
  ultra-dashboard:
    build: .
    image: ultra-dashboard:latest
    container_name: ultra_dashboard
    env_file: .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    restart: unless-stopped
    # Pas besoin d'exposer le port 3000 au public, Nginx s'en occupe en interne
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: ultra_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ultra-dashboard
    restart: unless-stopped
